AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Alessandrina serverless application.
Globals:
  Function:
    Timeout: 10
    Runtime: go1.x
    Architectures: [x86_64]
    Environment:
      Variables:
        DB_TABLE: !Ref BooksTable
        DB_CONNECTION: "aws"
        DB_LOG: "false"
    AutoPublishAlias: live
    DeploymentPreference:
      Type: !If [IsProduction, "Canary10Percent5Minutes", "AllAtOnce"]

Conditions:
  IsProduction: !Equals [!Ref "AWS::StackName", "alessandrina-prod"]

Resources:
  BooksAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      AccessLogSettings:
        DestinationArn: !GetAtt AccessLogGroup.Arn
        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","routeKey":"$context.routeKey","status":"$context.status","responseLatency":"$context.responseLatency","integrationRequestId":"$context.integration.requestId","functionResponseStatus":"$context.integration.status","integrationLatency":"$context.integration.latency","ip":"$context.identity.sourceIp","errorMessage":"$context.error.message","errorResponseType":"$context.error.responseType","integrationErrorMessage":"$context.integrationErrorMessage"}'

  AccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${AWS::StackName}/access_log"
      RetentionInDays: 7

  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST

  GetBooksFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      MemorySize: 128
      CodeUri: .
      Handler: get-books
      Description: Retrieve all books
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref BooksAPI
            Path: /books
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:Scan
              Resource: !GetAtt BooksTable.Arn

  GetBooksLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetBooksFunction}"
      RetentionInDays: 7

  GetBookFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      MemorySize: 256
      CodeUri: .
      Handler: get-book
      Description: Retrieve a book
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref BooksAPI
            Path: /books/{id}
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:GetItem
              Resource: !GetAtt BooksTable.Arn

  GetBookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetBookFunction}"
      RetentionInDays: 7

  CreateBookFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      MemorySize: 128
      CodeUri: .
      Handler: create-book
      Description: Create a new book
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref BooksAPI
            Path: /books
            Method: POST
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:PutItem
              Resource: !GetAtt BooksTable.Arn

  CreateBookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CreateBookFunction}"
      RetentionInDays: 7

  DeleteBookFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      MemorySize: 128
      CodeUri: .
      Handler: delete-book
      Description: Delete a book
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref BooksAPI
            Path: /books/{id}
            Method: DELETE
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:DeleteItem
              Resource: !GetAtt BooksTable.Arn

  DeleteBookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${DeleteBookFunction}"
      RetentionInDays: 7

  ApplicationDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "${AWS::StackName}-dashboard"
      DashboardBody: !Sub >
        {
          "widgets": [
            {
              "height": 5,
              "width": 8,
              "y": 2,
              "x": 0,
              "type": "metric",
              "properties": {
                "legend": {
                  "position": "hidden"
                },
                "region": "${AWS::Region}",
                "liveData": false,
                "period": 60,
                "timezone": "UTC",
                "title": "Count: Sum",
                "view": "timeSeries",
                "stacked": false,
                "metrics": [["AWS/ApiGateway", "Count", "ApiId", "${BooksAPI}"]]
              }
            },
            {
              "height": 5,
              "width": 8,
              "y": 2,
              "x": 8,
              "type": "metric",
              "properties": {
                "legend": {
                  "position": "hidden"
                },
                "region": "${AWS::Region}",
                "liveData": false,
                "period": 60,
                "timezone": "UTC",
                "title": "5XXError: Sum",
                "view": "timeSeries",
                "stacked": false,
                "metrics": [["AWS/ApiGateway", "5xx", "ApiId", "${BooksAPI}"]]
              }
            },
            {
              "height": 5,
              "width": 8,
              "y": 2,
              "x": 16,
              "type": "metric",
              "properties": {
                "legend": {
                  "position": "hidden"
                },
                "region": "${AWS::Region}",
                "liveData": false,
                "period": 60,
                "timezone": "UTC",
                "title": "4XXError: Sum",
                "view": "timeSeries",
                "stacked": false,
                "metrics": [["AWS/ApiGateway", "4xx", "ApiId", "${BooksAPI}"]]
              }
            },
            {
              "height": 5,
              "width": 12,
              "y": 7,
              "x": 0,
              "type": "metric",
              "properties": {
                "metrics": [
                  [
                    "AWS/ApiGateway",
                    "Latency",
                    "ApiId",
                    "${BooksAPI}",
                    { "region": "${AWS::Region}", "stat": "p50", "label": "p50" }
                  ],
                  [
                    "...",
                    { "region": "${AWS::Region}", "stat": "p90", "label": "p90" }
                  ],
                  ["...", { "region": "${AWS::Region}", "stat": "p99", "label": "p99" }]
                ],
                "legend": {
                  "position": "bottom"
                },
                "region": "${AWS::Region}",
                "liveData": false,
                "period": 60,
                "timezone": "UTC",
                "title": "Latencies: percentiles",
                "view": "timeSeries",
                "stacked": false
              }
            },
            {
              "height": 5,
              "width": 12,
              "y": 7,
              "x": 12,
              "type": "metric",
              "properties": {
                "metrics": [
                  [
                    "AWS/ApiGateway",
                    "IntegrationLatency",
                    "ApiId",
                    "${BooksAPI}",
                    { "region": "${AWS::Region}", "stat": "p50", "label": "p50" }
                  ],
                  [
                    "...",
                    { "region": "${AWS::Region}", "stat": "p90", "label": "p90" }
                  ],
                  ["...", { "region": "${AWS::Region}", "stat": "p99", "label": "p99" }]
                ],
                "legend": {
                  "position": "bottom"
                },
                "region": "${AWS::Region}",
                "liveData": false,
                "period": 60,
                "timezone": "UTC",
                "title": "Integration Latencies: percentiles",
                "view": "timeSeries",
                "stacked": false
              }
            },
            {
              "height": 2,
              "width": 24,
              "y": 0,
              "x": 0,
              "type": "text",
              "properties": {
                "markdown": "#  HTTP API"
              }
            },
            {
              "height": 4,
              "width": 12,
              "y": 14,
              "x": 0,
              "type": "metric",
              "properties": {
                "metrics": [
                  [
                    "AWS/Lambda",
                    "Invocations",
                    "FunctionName",
                    "${GetBookFunction}",
                    { "region": "${AWS::Region}" }
                  ],
                  ["...", "${GetBooksFunction}", { "region": "${AWS::Region}" }],
                  ["...", "${CreateBookFunction}", { "region": "${AWS::Region}" }],
                  ["...", "${DeleteBookFunction}", { "region": "${AWS::Region}" }]
                ],
                "legend": {
                  "position": "right"
                },
                "region": "${AWS::Region}",
                "liveData": false,
                "timezone": "UTC",
                "title": "Invocations: Sum",
                "period": 60,
                "view": "timeSeries",
                "stacked": false,
                "stat": "Sum"
              }
            },
            {
              "height": 4,
              "width": 12,
              "y": 14,
              "x": 12,
              "type": "metric",
              "properties": {
                "metrics": [
                  [
                    "AWS/Lambda",
                    "Duration",
                    "FunctionName",
                    "${GetBookFunction}",
                    { "region": "${AWS::Region}" }
                  ],
                  ["...", "${GetBooksFunction}", { "region": "${AWS::Region}" }],
                  ["...", "${CreateBookFunction}", { "region": "${AWS::Region}" }],
                  ["...", "${DeleteBookFunction}", { "region": "${AWS::Region}" }]
                ],
                "legend": {
                  "position": "right"
                },
                "region": "${AWS::Region}",
                "liveData": false,
                "timezone": "UTC",
                "title": "Duration: Average",
                "period": 60,
                "view": "timeSeries",
                "stacked": false,
                "stat": "Average"
              }
            },
            {
              "height": 4,
              "width": 12,
              "y": 18,
              "x": 0,
              "type": "metric",
              "properties": {
                "metrics": [
                  [
                    "AWS/Lambda",
                    "Errors",
                    "FunctionName",
                    "${GetBookFunction}",
                    { "region": "${AWS::Region}" }
                  ],
                  ["...", "${GetBooksFunction}", { "region": "${AWS::Region}" }],
                  ["...", "${CreateBookFunction}", { "region": "${AWS::Region}" }],
                  ["...", "${DeleteBookFunction}", { "region": "${AWS::Region}" }]
                ],
                "legend": {
                  "position": "right"
                },
                "region": "${AWS::Region}",
                "liveData": false,
                "timezone": "UTC",
                "title": "Errors: Sum",
                "period": 60,
                "view": "timeSeries",
                "stacked": false,
                "stat": "Sum"
              }
            },
            {
              "height": 4,
              "width": 12,
              "y": 18,
              "x": 12,
              "type": "metric",
              "properties": {
                "metrics": [
                  [
                    "AWS/Lambda",
                    "Throttles",
                    "FunctionName",
                    "${GetBookFunction}",
                    { "region": "${AWS::Region}" }
                  ],
                  ["...", "${GetBooksFunction}", { "region": "${AWS::Region}" }],
                  ["...", "${CreateBookFunction}", { "region": "${AWS::Region}" }],
                  ["...", "${DeleteBookFunction}", { "region": "${AWS::Region}" }]
                ],
                "legend": {
                  "position": "right"
                },
                "region": "${AWS::Region}",
                "liveData": false,
                "timezone": "UTC",
                "title": "Throttles: Sum",
                "period": 60,
                "view": "timeSeries",
                "stacked": false,
                "stat": "Sum"
              }
            },
            {
              "height": 2,
              "width": 24,
              "y": 12,
              "x": 0,
              "type": "text",
              "properties": {
                "markdown": "# Lambda"
              }
            },
            {
              "height": 5,
              "width": 12,
              "y": 24,
              "x": 0,
              "type": "metric",
              "properties": {
                "metrics": [
                  [
                    "AWS/DynamoDB",
                    "SuccessfulRequestLatency",
                    "TableName",
                    "${BooksTable}",
                    "Operation",
                    "Scan"
                  ],
                  ["...", "DeleteItem"],
                  ["...", "GetItem"],
                  ["...", "PutItem"]
                ],
                "legend": {
                  "position": "bottom"
                },
                "region": "${AWS::Region}",
                "liveData": false,
                "timezone": "UTC",
                "title": "SuccessfulRequestLatency: Average",
                "period": 60,
                "view": "timeSeries",
                "stacked": false,
                "stat": "Average"
              }
            },
            {
              "height": 5,
              "width": 12,
              "y": 24,
              "x": 12,
              "type": "metric",
              "properties": {
                "metrics": [
                  [
                    "AWS/DynamoDB",
                    "ReturnedItemCount",
                    "TableName",
                    "${BooksTable}",
                    "Operation",
                    "Scan"
                  ]
                ],
                "legend": {
                  "position": "bottom"
                },
                "region": "${AWS::Region}",
                "liveData": false,
                "timezone": "UTC",
                "title": "ReturnedItemCount: Sum",
                "period": 60,
                "view": "timeSeries",
                "stacked": false,
                "stat": "Sum"
              }
            },
            {
              "height": 5,
              "width": 12,
              "y": 29,
              "x": 0,
              "type": "metric",
              "properties": {
                "metrics": [
                  [
                    "AWS/DynamoDB",
                    "ConsumedReadCapacityUnits",
                    "TableName",
                    "${BooksTable}",
                    { "region": "${AWS::Region}" }
                  ]
                ],
                "legend": {
                  "position": "bottom"
                },
                "region": "${AWS::Region}",
                "liveData": false,
                "timezone": "UTC",
                "title": "ConsumedReadCapacityUnits: Sum",
                "period": 60,
                "view": "timeSeries",
                "stacked": false,
                "stat": "Sum"
              }
            },
            {
              "height": 5,
              "width": 12,
              "y": 29,
              "x": 12,
              "type": "metric",
              "properties": {
                "metrics": [
                  [
                    "AWS/DynamoDB",
                    "ConsumedWriteCapacityUnits",
                    "TableName",
                    "${BooksTable}",
                    { "region": "${AWS::Region}", "color": "#d62728" }
                  ]
                ],
                "legend": {
                  "position": "bottom"
                },
                "region": "${AWS::Region}",
                "liveData": false,
                "timezone": "UTC",
                "title": "ConsumedWriteCapacityUnits: Sum",
                "period": 60,
                "view": "timeSeries",
                "stacked": false,
                "stat": "Sum"
              }
            },
            {
              "height": 2,
              "width": 24,
              "y": 22,
              "x": 0,
              "type": "text",
              "properties": {
                "markdown": "# DynamoDB"
              }
            }
          ]
        }

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for the Books API"
    Value: !Sub "https://${BooksAPI}.execute-api.${AWS::Region}.amazonaws.com/"

  DashboardURL:
    Description: "Dashboard URL"
    Value: !Sub "https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${ApplicationDashboard}"

  GetBooksFunction:
    Description: "GetBooks Lambda Function ARN"
    Value: !GetAtt GetBooksFunction.Arn

  GetBookFunction:
    Description: "GetBook Lambda Function ARN"
    Value: !GetAtt GetBookFunction.Arn

  CreateBookFunction:
    Description: "CreateBook Lambda Function ARN"
    Value: !GetAtt CreateBookFunction.Arn

  DeleteBookFunction:
    Description: "DeleteBook Lambda Function ARN"
    Value: !GetAtt DeleteBookFunction.Arn
