AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Alessandrina serverless application.
Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Runtime: go1.x
    Tracing: Active
    Architectures: [x86_64]
    Environment:
      Variables:
        TABLE_NAME: !Ref BooksTable
        AWS_ENDPOINT_DEBUG: ""
        AWS_CLIENT_DEBUG: false
    AutoPublishAlias: !Ref Environment
    DeploymentPreference:
      Type: AllAtOnce

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: Environment of this stack of resources

Resources:
  BooksAPI:
    Type: AWS::Serverless::HttpApi

  BooksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10

  CreateBookFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: create-book
      Description: Create a new book
      Environment:
        Variables:
          STORAGE_MEMORY: false
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref BooksTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref BooksAPI
            Path: /books
            Method: POST

  GetBookFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: get-book
      Description: Retrieve a book
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BooksTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref BooksAPI
            Path: /books/{id}
            Method: GET

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for the Books API"
    Value: !Sub "https://${BooksAPI}.execute-api.${AWS::Region}.amazonaws.com/"

  CreateBookFunction:
    Description: "CreateBook Lambda Function ARN"
    Value: !GetAtt CreateBookFunction.Arn

  GetBookFunction:
    Description: "GetBook Lambda Function ARN"
    Value: !GetAtt GetBookFunction.Arn
