// Code generated by mockery v2.30.16. DO NOT EDIT.

package validation

import mock "github.com/stretchr/testify/mock"

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: v
func (_m *MockValidator) Check(v interface{}) error {
	ret := _m.Called(v)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockValidator_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockValidator_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - v interface{}
func (_e *MockValidator_Expecter) Check(v interface{}) *MockValidator_Check_Call {
	return &MockValidator_Check_Call{Call: _e.mock.On("Check", v)}
}

func (_c *MockValidator_Check_Call) Run(run func(v interface{})) *MockValidator_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockValidator_Check_Call) Return(_a0 error) *MockValidator_Check_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_Check_Call) RunAndReturn(run func(interface{}) error) *MockValidator_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
