name: Manual Load Testing

on:
  workflow_dispatch:
    inputs:
      SLO_TEST:
        description: 'SLO test: slo30sec5vus, slo30sec10vus, slo30sec15vus'
        required: false
        default: 'slo30sec5vus'

env:
    DEV_REGION: us-east-1
    DEV_STACK_NAME: alessandrina-dev
    DEV_PIPELINE_EXECUTION_ROLE: ${{ secrets.DEV_PIPELINE_EXECUTION_ROLE }}
    SLO_TEST: ${{ github.event.inputs.SLO_TEST }}

permissions:
  id-token: write
  contents: read

jobs:
  load-tests:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container: artilleryio/artillery:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume the dev pipeline user role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.DEV_REGION }}
          role-to-assume: ${{ env.DEV_PIPELINE_EXECUTION_ROLE }}
          role-session-name: load-testing
          role-skip-session-tagging: true

      - name: Extract API URL and save for the next "integration tests" step
        run: |
          API_URL=$(sam list stack-outputs --stack-name ${DEV_STACK_NAME} --region ${DEV_REGION} --output json | jq -r '.[] | select(.OutputKey=="WebEndpoint")|.OutputValue')
          echo "API_URL=${API_URL%/}" >> $GITHUB_ENV

      - name: Install additional dependencies
        run: npm install -g artillery-plugin-expect artillery-plugin-ensure

      - name: Make reports directory
        run: mkdir reports

      - name: Execute smoke test
        run: |
          API_URL=${{ env.API_URL }} /home/node/artillery/bin/run run --output reports/smoke.json tests/performance/smoke.yml
          /home/node/artillery/bin/run report --output reports/smoke.html reports/smoke.json

      - name: Execute SLO test
        run: |
          API_URL=${{ env.API_URL }} /home/node/artillery/bin/run run --output reports/${{ env.SLO_TEST }}.json --environment=${{ env.SLO_TEST }} tests/performance/slo.yml
          /home/node/artillery/bin/run report --output reports/${{ env.SLO_TEST }}.html reports/${{ env.SLO_TEST }}.json

      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: artillery-test-report
          path: reports/*
