name: Load Testing API

on:
  workflow_dispatch:
    inputs:
      API_URL:
        description: 'URL of the API to test'
        required: true
        default: ''

permissions:
  id-token: write
  contents: read

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make reports directory
        run: mkdir reports

      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.44.0/k6-v0.44.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1

      - name: Run k6 local test
        run: |
          API_URL=${{ github.event.inputs.API_URL }} ./k6 run tests/performance/single.js
          mv single.html reports/single.html

      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: k6
          path: reports/*
